#!/bin/bash

cd `dirname $0`

. ./common.sh

RCLONE=./rclone

if [[ "$RESTIC_ARCHIVE_REPOSITORY" =~ ^/ ]] && \
	[[ -n "$RCLONE_ARCHIVE_REPOSITORY" ]]
then
	$RCLONE sync $RESTIC_ARCHIVE_REPOSITORY $RCLONE_ARCHIVE_REPOSITORY
fi

if [[ "$RESTIC_TRANSIENT_REPOSITORY" =~ ^/ ]] && \
	[[ "$RESTIC_TRANSIENT_REPOSITORY" != "$RESTIC_ARCHIVE_REPOSITORY" ]] && \
	[[ -n "$RCLONE_TRANSIENT_REPOSITORY" ]]
then
	$RCLONE sync $RESTIC_TRANSIENT_REPOSITORY $RCLONE_TRANSIENT_REPOSITORY
fi
